version: 0.0
os: linux

files:
  - source: springbootApp.jar
    destination: /root
#  - source: /index.jsp
#    destination: /home/ec2-user/tomcat/webapps/
#  - source: /dbtest.jsp
#    destination: /root/tomcat/webapps/ROOT
    
hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
#  ApplicationStop:
#    - location: server_stop.sh
#      timeout: 300
#      runas: root
